
Programa ::= Principal
Principal
         ::= 'programa' 'id' '{' VARS? FUNCIONES? DIBUJA '}'

VARS
  ::= 'vars' ( ( '[' VARCTE ']' | 'id' | 'id' ',' )+ ':' TIPO ';' )*

TIPO
  ::= (Bool | Num | Texto )

FUNCIONES
  ::= 'funcion' TIPO '{' ESTATUTO*  'return' VARCTE '}' 

ESTATUTO
  ::= ( ASIGNACION | CONDICION | ESCRITURA | CICLOS )

ASIGNACION
  ::= 'id' '=' EXPRESION ';'

EXPRESION
  ::= EXP ( ( '<' | '>' | '!=' | ) EXP )? 

EXP
  ::= (TERMINO ('+' | '-')? )+

TERMINO
  ::= (FACTOR ('*' | '/')? )+

FACTOR
  ::= ('{' EXPRESION '}' ) | ( ( '+' | '-' )? VARCTE) 

CONDICION 
  ::= 'si' '(' EXPRESION ')' '{' BLOQUE '}' ( 'sino' '{' ESTATUTO* '}' )? 

ESCRITURA
  ::= 'muestra' '(' ('CteTexto' | EXPRESION )+ ')' ';'

CICLOS
  ::= (MIENTRAS | HAZ | POR)

MIENTRAS 
  ::= 'mientras' '(' EXPRESION ')' '{' ESTATUTO* '}' 

HAZ
  ::= 'haz' '{' ESTATUTO* '}' 'mientras' '(' EXPRESION ')' 

POR
  ::= 'por' '(' EXPRESION ':' EXPRESION ')' '{' ESTATUTO* '}' 







